FROM python:3.10-alpine

# Nastavení pracovního adresáře ve složce /code
WORKDIR /code

RUN apk update && \
    apk add --no-cache mariadb-connector-c-dev build-base

# Kopírování souboru s požadavky do pracovního adresáře
COPY requirements.txt .

# Instalace požadovaných balíčků
RUN pip install -r requirements.txt

# Kopírování zbylých souborů do pracovního adresáře
COPY . .

# Nastavení proměnné prostředí pro FastAPI
ENV PORT=8000
ENV MODULE_NAME=app
ENV TZ=Europe/Prague

# Exponování portu, na kterém bude FastAPI naslouchat
EXPOSE $PORT

# Spuštění FastAPI aplikace pomocí uvicorn
CMD ["uvicorn", "--host", "0.0.0.0", "--port", "8000", "app:app"]