version: '3'

services:
  #app:
   # build: .
   # ports:
    #  - "8000:8000"
    #depends_on:
     # - mariadb

  mariadb:
    image: mariadb
    restart: always
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: fin_db
      MYSQL_USER: tomino
      MYSQL_PASSWORD: 123

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: secret